#macro MENU_MARGIN  (6)
#macro MENU_PADDING (6)

#macro MENU_X1       (0 + MENU_MARGIN)
#macro MENU_X2       (CAMERA_WIDTH - MENU_MARGIN)
#macro MENU_MIDDLE_X (CAMERA_WIDTH / 2)

#macro MENU_Y1       (0 + MENU_MARGIN) 
#macro MENU_Y2       (CAMERA_HEIGHT - MENU_MARGIN)
#macro MENU_MIDDLE_Y (CAMERA_HEIGHT / 2)
