#macro MENU_MARGIN (9)

#macro MENU_X1 (UI_X1 + MENU_MARGIN)
#macro MENU_Y1 (UI_Y1 + MENU_MARGIN)
#macro MENU_X2 (UI_X2 - MENU_MARGIN)
#macro MENU_Y2 (UI_Y2 - MENU_MARGIN)

#macro MENU_ELEMENT_MARGIN  (9)
#macro MENU_ELEMENT_PADDING (9)

#macro MENU_ELEMENT_HEIGHT ((MENU_ELEMENT_PADDING * 2) + string_height("HEIGHT"))
